version: "3.9"

services:
  eureka:
    image: registration
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.instance.preferIPAddress=true
    ports:
    - "8761:8761"
  web:
    image: web
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.instance.preferIPAddress=true
    ports:
    - "4444:4444"
    links:
    - eureka
    depends_on:
    - eureka
    - redact
    - pdf
  redact:
    image: redact
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.instance.preferIPAddress=true
    ports:
    - "2222:2222"
    links:
    - eureka
    depends_on:
    - eureka
  pdf:
    image: pdf
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.instance.preferIPAddress=true
    ports:
    - "3333:3333"
    links:
    - eureka
    depends_on:
    - eureka
