apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eureka
  name: eureka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/cwk-i-vjosashalasahiti-second-default: "true"
        io.kompose.service: eureka
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka:8761/eureka/
            - name: eureka.instance.preferIPAddress
              value: "true"
          image: registration
          name: eureka
          ports:
            - containerPort: 8761
              hostPort: 8761
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
